// pages/index.tsx
import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Hero from '@/components/Hero';
import Features from '@/components/Features';
import TeamFeatures from '@/components/TeamFeatures';
import Banner1 from '@/components/Banner1';
import BrandGrid from '@/components/BrandGrid';
import Events from '@/components/Events';
import Banner2 from '@/components/Banner2';
import QuoteForm from '@/components/QuoteForm';
import Download from '@/components/Download';
import Gallery from '@/components/Gallery';
import FeatureGrid from '@/components/FeatureGrid';
import Testimonials from '@/components/Testimonials';
import Tab from '@/components/Tab';
import Scooter from '@/components/Scooter';
import CardTestimonal from '@/components/CardTestimonal';
import FAQ from '@/components/FAQ';
import Query from '@/components/Query';
import Footer from '@/components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Motorbike Landing Page</title>
        <meta name="description" content="Generated by Figma" />
        <link rel="icon" href="public/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Hero />
        <Features />
        <TeamFeatures />
        <Banner1 />
        <BrandGrid />
        <Events />
        <Banner2 />
        <QuoteForm />
        <Download />
        <Gallery />
        <FeatureGrid />
        <Testimonials />
        <Tab />
        <Scooter />
        <CardTestimonal />
        <FAQ />
        <Query />
      </main>
      <Footer />
    </>
  );
}
